CREATE TABLE ARTICLE (
     ARTICLE_ID  IDENTITY        NOT NULL    PRIMARY KEY,
     TITLE       VARCHAR(255)    NOT NULL,
     CONTENTS    VARCHAR(1000)    NOT NULL
);

CREATE TABLE ARTICLE_IMAGE (
    ARTICLE_IMAGE_ID    IDENTITY            NOT NULL    PRIMARY KEY,
    ARTICLE_ID          BIGINT              NOT NULL,
    NAME                VARCHAR(300)        NOT NULL,
    URL                 VARCHAR(1000)       NOT NULL,
    ORDERS              INTEGER             NOT NULL,
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE(ARTICLE_ID)
);


CREATE TABLE ARTICLE_COMMENT (
    ARTICLE_COMMENT_ID      IDENTITY            NOT NULL    PRIMARY KEY,
    ARTICLE_ID              BIGINT              NOT NULL,
    CONTENTS                VARCHAR(1000)       NOT NULL,
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE(ARTICLE_ID)
);
